services:
  db:
    container_name: movim_db
    hostname: movim-db
    image: docker.io/library/postgres:18.3-alpine3.23
    environment:
      POSTGRES_USER: movim
      POSTGRES_PASSWORD: movim
      POSTGRES_DB: movim
    command: ["postgres", "-c", "shared_buffers=64MB", "-c", "work_mem=4MB", "-c", "effective_cache_size=256MB", "-c", "max_connections=30"]
    networks:
      caddy:
        ipv4_address: 172.16.0.4
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
          interval: 2s
    restart: unless-stopped
  app:
    container_name: movim_app
    hostname: movim-app
    build:
      context: ./
      dockerfile: Containerfile
    depends_on:
      movim_db:
        condition: service_healthy
    volumes:
      - .env.example:/usr/local/share/movim/.env:ro
    environment:
      DB_HOST: movim-db
      DAEMON_URL: https://127.0.0.1:8080/
      DAEMON_DEBUG: true
      DAEMON_VERBOSE: true
    ports:
      - 8080:8080
